/**
 * Autogenerated file. Generated at 28/01/2025, 5:56:17 pm.
 * Do not edit!
 */

/** @type {import('tailwindcss').Config} */

import base from "./tailwind.base.js";

export default {
  // Merge or override the base darkMode if desired
  darkMode: base.darkMode,

  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],

  plugins: [
    // e.g. ...base.plugins if base had them
    // require("@tailwindcss/typography")
  ],

  theme: {
    // Spread everything from base.theme
    ...base.theme,

    extend: {
      ...(base.theme?.extend || {}),

      // Example if you wanted a custom brand color
      // colors: {
      //   ...(base.theme?.extend?.colors || {}),
      //   brand: "#A855F7"
      // }
    },
  },
};
